language: php
dist: trusty

php: 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - yes | pecl install mcrypt-snapshot
  - composer validate --ansi
  - composer global require hirak/prestissimo

install: composer install

before_script: composer phpcs

script: ./bin/self-test
